config/routes.rb
Events::Application.routes.draw do

 # get "bienvenue" => "bienvenue#index"
  root 'bienvenue#index'
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  resources :events

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bienvenue_controller.rb
class BienvenueController < ApplicationController
	def index
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def index
		#binding.pry
		@events = Event.all
			end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bienvenue_helper.rb
module BienvenueHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/bienvenue/index.html.erb
<h1>Bienvenue sur le site des évènements</h1>

<%= link_to "Evénements", events_path %>

app/views/events/index.html.erb
<h1>Liste des événements</h1>

<h2><%= pluralize(@events.size, 'Evènement')%></h2>
<ul>
	<% @events.each do |e| %>
	<li> <strong><%= e.name %></strong> in <%= e.location %> <%= number_to_currency (e.price), unit: " €", format: "%n %u" %><br>
		Description: <br><%= truncate(e.description)%></li>
	<% end %>

</ul>

<%=link_to "Bienvenue", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Events</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>